- name: copy file from master to node
  hosts: remote
  become: yes

  tasks: 
  - name: copy the file
    ansible.builtin.copy:

     src: /home/node/file2.txt
     dest: /home/node/tmp/.
     remote_src: yes
