- name: copy file from master to node
  hosts: localhost
  become: yes

  tasks: 
  - name: copy the file
    ansible.builtin.copy

     src: /home/ashok/ansible/nginx.yaml
     dest: /home/node/tmp