- name: convert dictionary into items/list
  hosts: localhost
  vars:
    my_dict: #this is called dictionary or map or key /value pairs
      course: Ansible
      trainer: shivakumar
      duration: 120Hr
  tasks:
   - name: before convert
     ansible.builtin.debug:
      msg: "Before convert:{{my_dict}}" 
   - name: after convert
     ansible.builtin.debug:
      msg: "After convert:{{ my_dict | disc2items }}"
   

