- name: convert dictionary into items/list
  hosts: localhost
  vars:
    my_dict: #this is called dictionary or map or key /value pairs
      course: Ansible
      trainer: shivakumar
      duration: 120Hr
  tasks:
   - name: before convert
     ansible.builtin.debug:
      msg: "Before convert:{{my_dict}}" 
   - name: after convert
     ansible.builtin.debug:
      msg: "After convert: {{ my_dict | dict2items }}"
   

 - name: convert items into dictonaries
   host: localhost
   vars: 
    my_list:
     - {'key': 'Course', 'value': 'Ansbile'}
     - {'key': 'Trainer', 'value': 'Sivakumar'}
     - {'key': 'Duration', 'value': '120hr'}

   tasks:
   - name: before convert
     ansible.builtin.debug:
      msg: "Before convert:{{my_list}}"
   - name: after convert
     ansible.builtin.debug:
      msg: "after convert: {{ my_list | items2dict }}"     
