- name: variables
  hosts: mylocal
  vars: #variable declaration
     course: "Terraform"
     Trainer: "shiva"
     duration: "3 Months"

  tasks:
  - name: print information
    ansible.builtin.debug:
         msg: "Hi we are leasring {{course}}  with {{Trainer}}  duration {{duration}}"
     