- name: variables from inventory
  hosts: localhost
  tasks:
  - name: print information
    vars:
      timings: "07:15 to 08:30"
    ansible.builtin.debug:
       ansible:  "Hi I am learing {{course}}  with trainer {{}} with timings {{duration}}"  