- name: variables from files
  hosts: localhost
  vars_files: 
   -vars.yaml
  tasks: 
   - name: print override inforation
     ansible.builtin.debug:
         msg: "hi we are learning {{devops}} course from trainer {{trainer}},with duration {{duration}}" 