- name: variables
  hosts: localhost
  vars: #variables declaration
   course: "Teraform"
   trainer: "shiva"
   duration: "15hours"

  tasks: 
    - name: prints override information
      vars: #task level variables
       course: "devops"
      ansible.builtin.debug:
       msg: "Hi we are learning {{course}},with trainer {{trainer}},duration is {{duration}}"


    - name: print information
      ansible.builtin.debug:
        msg: "hi we are learning {{course}},with  trainer {{trainer}} duration {{duration}} "
