- name: variables from inventory
  hosts: localhost
  tasks:
   - name: print information
     vars:
     ansible.builtin.debug:
      msg: "hi we are learning {{course}},with  trainer {{trainer}} duration {{duration}}"