- name: variables from inventory
  hosts: localhost
  tasks:
  - name: print information
    vars:
      timings: "07:15 to 08:30"
    ansible.builtin.debug:
       msg: "Hi I am learing {{Course}}  with trainer {{Trainer}} and duration {{Duration}}  with {{timings}} "  